name: Vampcraft
version: "1.0"
api-version: "1.12"
author: 7isenko
main: io.github._7isenko.vampcraft.Vampcraft
commands:
  vamp:
    description: sets player as vampire
    usage: /vamp <player>
    permission: op